version: 2.1

jobs:
  run-service:
    docker:
      - image: circleci/node:16.13.0-bullseye-browsers-legacy
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: check directory
          command: |
            pwd && ls
      - run:
          name: install dependencies
          command: |
            yarn install
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run:
          name: Access Server
          command: |
            ssh -oStrictHostKeyChecking=no $USER@$DOMAIN_NAME ls
      - run:
          name: redirect to project and install
          command: |
            cd codes/manage-nginx && yarn install
workflows:
  push:
    jobs:
      - run-service:
          filters:
            branches:
              only:
                - /.*/
